
#ifndef NBGLUELIBJPEGWRITE_H_INCLUIDO
#define NBGLUELIBJPEGWRITE_H_INCLUIDO

#ifndef CONFIG_NB_UNSUPPORT_INTERNAL_LIBJPEG
void NBGlueLibJpegWrite_linkToMethods();
#endif //#ifndef CONFIG_NB_UNSUPPORT_INTERNAL_LIBJPEG

#endif
